language: cpp
os: linux
dist: xenial

install:
- |
  set -e
  wget http://kayari.org/gcc-latest/gcc-latest.deb
  sudo dpkg -i gcc-latest.deb
  set +e

env:
  - PATH=/opt/gcc-latest/bin:$PATH LD_RUN_PATH=/opt/gcc-latest/lib64

script:
- |
  g++ -v
  make check-werror
