language: cpp
os: linux
dist: xenial

install:
- |
  set -e
  wget http://kayari.org/gcc-latest/gcc-latest.deb
  sudo dpkg -i gcc-latest.deb
  sudo ln -s /opt/gcc-latest/bin/gcc /usr/bin/gcc-latest
  sudo ln -s /opt/gcc-latest/bin/g++ /usr/bin/g++-latest
  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-latest 90 --slave /usr/bin/g++ g++ /usr/bin/g++-latest
  sudo ldconfig /opt/gcc-latest/lib64
  set +e

script:
- |
  g++ -v
  make check-werror
