language: cpp
os: linux
dist: xenial

install:
- |
  wget http://kayari.org/gcc-latest/gcc-latest.deb \
  && sudo dpkg -i gcc-latest.deb
  export PATH=/opt/gcc-latest/bin:$PATH
  export LD_RUN_PATH=/opt/gcc-latest/lib64

script:
- |
  g++ -v
  which gcc
  echo $LD_RUN_PATH
  make check-werror
